<?php

return array (
  'backend' => 
  array (
    'courses' => 
    array (
      'title' => 'Kursus',
      'fields' => 
      array (
        'published' => 'Diterbitkan',
        'featured' => 'Percuma',
        'free' => 'Percuma',
        'trending' => 'Berbayar',
        'popular' => 'Trending',
        'teachers' => 'Pengajar',
        'category' => 'Kategori',
        'title' => 'Tajuk',
        'slug' => 'Slug',
        'description' => 'Huraian',
        'price' => 'Harga',
        'course_image' => 'Gambar kursus',
        'start_date' => 'Tarikh Mula',
        'meta_title' => 'Meta Tajuk',
        'meta_description' => 'Meta Huraian',
        'meta_keywords' => 'Meta Keywords',
        'sidebar' => 'Tambah Sidebar',
        'lessons' => 
        array (
          'add' => 'Tambah Subtopik',
          'view' => 'Papar Subtopik',
        ),
        'course' => 'Kursus',
        'status' => 'Status',
      ),
      'add_teachers' => 'Tambah pengajar',
      'add_categories' => 'Tambah kategori',
      'slug_placeholder' => 'Input slug atau akan dihasilkan secara automatik',
      'select_category' => 'Pilih Kategori',
      'select_teachers' => 'Pilih Pengajar',
      'test' => 'Ujian',
      'lesson' => 'Subtopik',
      'create' => 'Cipta Kursus',
      'edit' => 'Ubah Kursus',
      'view' => 'Papar Kursus',
      'category' => 'Kategori',
      'save_timeline' => 'Simpan timeline',
      'course_timeline' => 'Timeline kursus',
      'timeline_description' => 'Tarik dan ubah urutan Pelajaran / Ujian untuk kursus',
      'listing_note' => 'Hanya Pelajaran dan Ujian yang Diterbitkan yang akan Dipaparkan dan Disusun.',
    ),
    'tests' => 
    array (
      'title' => 'Ujian',
      'fields' => 
      array (
        'course' => 'Kursus',
        'lesson' => 'Subtopik',
        'title' => 'Tajuk',
        'description' => 'Huraian',
        'published' => 'Terbit',
        'questions' => 'Soalan',
      ),
      'create' => 'Cipta Ujian',
      'edit' => 'Ubah Ujian',
      'view' => 'Papar Ujian',
    ),
    'orders' => 
    array (
      'fields' => 
      array (
        'payment_status' => 
        array (
          'pending' => 'Dalam proses',
          'completed' => 'Lengkap',
          'failed' => 'Gagal',
          'title' => 'Pembayaran',
        ),
        'payment_type' => 
        array (
          'stripe' => 'Credit / Debit Card (Stripe Payment Gateway)',
          'paypal' => 'Paypal',
          'offline' => 'Offline',
          'title' => 'Payment Type',
        ),
        'reference_no' => 'Nombor rujukan.',
        'ordered_by' => 'Disusun mengikuti',
        'items' => 'Barang',
        'amount' => 'Jumlah',
        'user_email' => 'e-mel pengguna',
        'date' => 'Tarikh pesanan',
      ),
      'complete' => 'Selesaikan Secara Manual',
      'offline_requests' => 'Permintaan Offline',
      'view_invoice' => 'Papar Invoice',
      'download_invoice' => 'Download Invoice',
      'title' => 'Orders',
    ),
    'pages' => 
    array (
      'fields' => 
      array (
        'published' => 'Terbit',
        'drafted' => 'Drafted',
        'title' => 'Tajuk',
        'slug' => 'Slug',
        'featured_image' => 'Gambar pilihan',
        'content' => 'Kandungan',
        'meta_title' => 'Meta Tajuk',
        'meta_description' => 'Meta Huraian',
        'meta_keywords' => 'Meta Keywords',
        'clear' => 'Clear',
        'status' => 'Status',
        'created' => 'Dicipta',
        'created_at' => 'Dicipta pada',
      ),
      'max_file_size' => '(max file size 10MB)',
      'title' => 'Pages',
      'create' => 'Cipta Page',
      'edit' => 'Ubah Page',
      'view' => 'Papar Pages',
    ),
    'access' => 
    array (
      'users' => 
      array (
        'user_actions' => 'User Actions',
        'management' => 'User Management',
        'change_password' => 'Tukar Password',
        'change_password_for' => 'Tukat Password untuk :user',
        'create' => 'Cipta User',
        'table' => 
        array (
          'abilities' => 'Abilities',
          'total' => 'user total|users total',
          'confirmed' => 'Disahkan',
          'created' => 'Dicipta',
          'email' => 'E-mail',
          'id' => 'ID',
          'last_updated' => 'Terakhir dikemas kini',
          'name' => 'Nama',
          'first_name' => 'Nama pertama',
          'last_name' => 'Nama terakhir',
          'no_deactivated' => 'No Pengguna yang Dinyahaktifkan',
          'no_deleted' => 'No Pengguna yang Dihapuskan',
          'other_permissions' => 'Kebenaran Lain',
          'permissions' => 'Kebenaran',
          'roles' => 'Roles',
          'social' => 'Social',
          'status' => 'Status',
        ),
        'all_permissions' => 'Semua Kebenaran',
        'deactivated' => 'Pengguna yang Dinyahaktifkan',
        'deleted' => 'Pengguna yang Dihapuskan',
        'edit' => 'Edit User',
        'active' => 'Active Users',
        'view' => 'Papar User',
        'tabs' => 
        array (
          'titles' => 
          array (
            'overview' => 'Overview',
            'history' => 'History',
          ),
          'content' => 
          array (
            'overview' => 
            array (
              'avatar' => 'Avatar',
              'confirmed' => 'Disahkan',
              'created_at' => 'Dicipta pada',
              'deleted_at' => 'Dipadamkan pada',
              'email' => 'E-mail',
              'last_login_at' => 'Log Masuk Terakhir Pada',
              'last_login_ip' => 'IP Log Masuk Terakhir',
              'last_updated' => 'Terakhir dikemas kini',
              'name' => 'Nama',
              'first_name' => 'Nama pertama',
              'last_name' => 'Nama terakhir',
              'status' => 'Status',
              'timezone' => 'Timezone',
            ),
          ),
        ),
        'no_permissions' => 'Tiada Kebenaran',
        'no_roles' => 'Tiada Peranan untuk ditetapkan.',
        'permissions' => 'Keberanan',
      ),
      'roles' => 
      array (
        'management' => 'Role Management',
        'create' => 'Cipta Role',
        'edit' => 'Edit Role',
        'table' => 
        array (
          'total' => 'role total|roles total',
          'number_of_users' => 'Jumlah Users',
          'permissions' => 'Kebenaran',
          'role' => 'Role',
          'sort' => 'Susun',
        ),
      ),
    ),
    'blogs' => 
    array (
      'fields' => 
      array (
        'title' => 'Tajuk',
        'category' => 'Kategori',
        'slug' => 'Slug',
        'featured_image' => 'Gambar',
        'content' => 'Content',
        'tags_placeholder' => 'Tambah tags disini',
        'meta_title' => 'Meta Tajuk',
        'meta_description' => 'Meta huraian',
        'meta_keywords' => 'Meta Keywords',
        'publish' => 'Terbit',
        'clear' => 'Clear',
        'status' => 'Status',
        'views' => 'Papar',
        'created' => 'Cipta',
        'comments' => 'Komen',
        'tags' => 'Tags',
        'created_at' => 'Dicipta pada',
      ),
      'max_file_size' => '(max file size 10MB)',
      'title' => 'Blog',
      'create' => 'Cipta Blog',
      'edit' => 'Edit Blog',
      'view' => 'Papar Blogs',
    ),
    'lessons' => 
    array (
      'slug_placeholder' => 'Input slug or it will be generated automatically',
      'fields' => 
      array (
        'course' => 'Kursus',
        'title' => 'Tajuk',
        'slug' => 'Slug',
        'lesson_image' => 'Gambar Lesson',
        'short_text' => 'Huraian pendek',
        'full_text' => 'Maklumat sampingan',
        'downloadable_files' => 'Downloadable Files',
        'free_lesson' => 'Free Lesson',
        'published' => 'Diterbitkan',
        'position' => 'Position',
        'youtube_videos' => 'YouTube Videos',
        'add_pdf' => 'Tambah PDF',
        'add_video' => 'Tambah Video',
        'media_video' => 'Media Video',
        'media_audio' => 'Media Audio',
        'media_pdf' => 'Media PDF',
        'add_audio' => 'Tambah Audio',
      ),
      'max_file_size' => '(max file size 5MB)',
      'short_description_placeholder' => 'Masukkan penerangan ringkas pelajaran',
      'select_course' => 'Pilih Kursus',
      'yt_note' => '<b>Instructions to add Video link: </b><br> Go to youtube -> open video -> right click on video and <b>Copy Video URL</b> and paste here.<br> If you want to add multiple videos, then separate them with <b>,</b> (Comma) Sign.',
      'vimeo_note' => '<b>Instructions to add Video link: </b><br> Go to vimeo -> open video -> right click on video and <b>Copy Video URL</b> and paste here.<br> If you want to add multiple videos, then separate them with <b>,</b> (Comma) Sign.',
      'title' => 'Subtopik',
      'enter_video_url' => 'Enter video data',
      'enter_video_embed_code' => 'Enter video embed code',
      'create' => 'Cipta Lessons',
      'edit' => 'Edit Lessons',
      'view' => 'View Lessons',
      'video_guide' => '<p class="mb-1"><b>Youtube :</b> Go to Youtube -> Go to video you want to display -> click on share button below video. Copy that links and paste in above text box </p>
<p class="mb-1"><b>Vimeo :</b> Go to Vimeo -> Go to video you want to display -> click on share button and copy paste video url here </p>
<p class="mb-1"><b>Upload :</b> Upload <b>mp4</b> file in file input</p>
<p class="mb-1"><b>Embed :</b> Copy / Paste embed code in above text box</p>',
      'remove' => 'Buang',
    ),
    'categories' => 
    array (
      'fields' => 
      array (
        'name' => 'Nama',
        'select_icon' => 'Pilih Icon',
        'image' => 'Imej',
        'icon' => 'Icon',
        'icon_type' => 
        array (
          'title' => 'Jenis Icon',
          'select_any' => 'Pilih Mana-mana',
          'image' => 'Muat naik gambar',
          'icon' => 'Pilih Icon',
        ),
        'or' => 'Or',
        'slug' => 'Slug',
        'courses' => 'Kursus',
        'status' => 'Status',
      ),
      'title' => 'Kategori',
      'create' => 'Cipta Kategori',
      'edit' => 'Edit Kategori',
      'view' => 'Papar Kategori',
    ),
    'faqs' => 
    array (
      'fields' => 
      array (
        'question' => 'Soalan',
        'answer' => 'Jawapan',
        'category' => 'Kategori',
        'status' => 'Status',
      ),
      'title' => 'FAQs',
      'create' => 'Cipta FAQ',
      'edit' => 'Edit FAQ',
      'view' => 'Papar FAQs',
    ),
    'invoices' => 
    array (
      'fields' => 
      array (
        'view' => 'Papar',
        'download' => 'Download',
        'order_date' => 'Tarikh pesanan',
        'amount' => 'Jumlah',
      ),
      'title' => 'Invoices',
    ),
    'menu-manager' => 
    array (
      'title' => 'Menu Manager',
    ),
    'messages' => 
    array (
      'compose' => 'Compose',
      'search_user' => 'Cari User',
      'select_recipients' => 'Pilih Recipients',
      'start_conversation' => 'Mulakan perbualan',
      'type_a_message' => 'Taip mesej',
      'title' => 'Mesej',
    ),
    'questions' => 
    array (
      'fields' => 
      array (
        'question' => 'Soalan',
        'question_image' => 'Gambar soalan',
        'score' => 'Markah',
        'tests' => 'Ujian',
        'option_text' => 'Pilih Text',
        'correct' => 'Betul',
        'course' => 'Kursus',
        'lesson' => 'Lesson',
        'title' => 'Tajuk',
        'option_explanation' => 'Penjelasan Pilihan',
      ),
      'title' => 'Soalan',
      'create' => 'Cipta Soalan',
      'edit' => 'Edit Soalan',
      'view' => 'View Soalan',
      'test' => 'Ujian',
    ),
    'reasons' => 
    array (
      'fields' => 
      array (
        'title' => 'Tajuk',
        'icon' => 'Icon',
        'content' => 'Content',
        'status' => 'Status',
      ),
      'title' => 'Reasons',
      'create' => 'Cipta Reason',
      'edit' => 'Edit Reason',
      'view' => 'Papar Reasons',
      'note' => 'Sebab akan dipaparkan sebagai slaid di laman utama seperti di bawah',
    ),
    'general_settings' => 
    array (
      'title' => 'Umum',
      'contact' => 
      array (
        'short_text' => 'Short Text',
        'show' => 'Show',
        'primary_address' => 'Primary Address',
        'secondary_address' => 'Secondary Address',
        'primary_phone' => 'Primary Phone',
        'secondary_phone' => 'Secondary Phone',
        'primary_email' => 'Primary Email',
        'secondary_email' => 'Secondary Email',
        'location_on_map' => 'Location on Map',
        'map_note' => '<h3>How to embed Location for Map?</h3>
                                <p>Do following simple steps and you are good to go:</p>
                                <ol class="map-guide">
                                    <li>Go to <a class="text-bold" target="_blank" href="//maps.google.com">Google Map</a> </li>
                                    <li>Search the place you want to add by Entering address / location in input box located on upper-left corner</li>
                                    <li>Once you get the place you want. It shows details in left sidebar. Click on <i class="fa fa-share-alt text-primary"></i> button</li>
                                    <li>A popup will appear which will have two tabs <b>Send a link</b> and <b>Embed a Map</b></li>
                                    <li>Click on <b>Embed a map</b> It will show you chosen Place on Map</li>
                                    <li>Now click on the dropdown from the left. By default <b>Medium</b> is selected. Click on it and Select <b>Large</b></li>
                                    <li>Now Click on <b class="text-primary">COPY HTML</b> link from it and <b>Paste</b> that code here in <b>Location on Map</b>.</li>
                                </ol>',
        'title' => 'Contact',
        'primary_email_note' => 'This email will be used to correspond "Contact Us" emails',
      ),
      'footer' => 
      array (
        'short_description' => 'Huraian Pendek',
        'popular_categories' => 'Kategori Popular',
        'featured_courses' => 'Kursus Percuma',
        'trending_courses' => 'Kursus Berbayar',
        'popular_courses' => 'Kursus Popular',
        'custom_links' => 'Custom Links',
        'social_links' => 'Social Links',
        'link_url' => 'URL',
        'social_links_note' => 'Add social link URL and select Icon for that media from iconpicker. Click on <b>ADD +</b> button. And your social link will be created. You can also delete them by clicking on <b><i class="fa fa-times"></i></b> button',
        'newsletter_form' => 'Newsletter Form',
        'bottom_footer' => 'Bottom Footer',
        'bottom_footer_note' => 'Note : it includes Copyright text and Footer links',
        'copyright_text' => 'Copyright Text',
        'footer_links' => 'Footer Links',
        'link_label' => 'Label',
        'link' => 'Link',
        'title' => 'Footer',
        'section_1' => 'Section 1',
        'section_2' => 'Section 2',
        'section_3' => 'Section 3',
        'recent_news' => 'Recent News',
      ),
      'logos' => 
      array (
        'title' => 'Logos',
      ),
      'layout' => 
      array (
        'title' => 'Layout',
      ),
      'email' => 
      array (
        'title' => 'Mail Configuration',
        'mail_from_name' => 'Mail From Name',
        'mail_from_name_note' => 'This will be display name for your sent email.',
        'mail_from_address' => 'Mail From Address',
        'mail_from_address_note' => 'This email will be used for "Contact Form" correspondence.',
        'mail_driver' => 'Mail Driver',
        'mail_driver_note' => 'You can select any driver you want for your Mail setup. <b>Ex. SMTP, Mailgun, Mandrill, SparkPost, Amazon SES etc.</b><br> Add <b>single driver only</b>.',
        'mail_host' => 'Mail HOST',
        'mail_port' => 'Mail PORT',
        'mail_username' => 'Mail Username',
        'mail_username_note' => 'Add your email id you want to configure for sending emails',
        'mail_password' => 'Mail Password',
        'mail_password_note' => 'Add your email password you want to configure for sending emails',
        'mail_encryption' => 'Mail Encryption',
        'mail_encryption_note' => 'Use <b>tls</b> if your site uses <b>HTTP</b> protocol and <b>ssl</b> if you site uses <b>HTTPS</b> protocol',
        'note' => '<b>Important Note</b> : IF you are using <b>GMAIL</b> for Mail configuration, make sure you have completed following process before updating:
 <ul>
<li>Go to <a target="_blank" href="https://myaccount.google.com/security">My Account</a> from your Google Account you want to configure and Login</li>
<li>Scroll down to <b>Less secure app access</b> and set it <b>ON</b></li>
</ul>',
      ),
      'payment_settings' => 
      array (
        'title' => 'Payment Configuration',
        'select_currency' => 'Select Currency',
        'stripe' => 'Stripe Payment Method',
        'stripe_note' => 'Enables payments in site with Debit / Credit Cards',
        'paypal' => 'Paypal Payment Method',
        'paypal_note' => 'Redirects to paypal for payment',
        'offline_mode' => 'Offline Payment Method',
        'offline_mode_note' => 'User gets assistance for offline payment via admin',
        'key' => 'API Key',
        'secret' => 'API Secret',
        'client_id' => 'Client ID',
        'client_secret' => 'Secret',
        'mode' => 'Mode',
        'sandbox' => 'Sandbox',
        'live' => 'Live',
        'how_to_stripe' => 'How to get STRIPE API Credentials?',
        'how_to_paypal' => 'How to get PayPal API Credentials?',
        'mode_note' => '<b>Sandbox</b>= Will be used for testing payments with PayPal Test Credentials. Account with USD only can make payments with PayPal for now. This options will redirect to test PayPal payment with Sandbox User Credentials. It will be used for dummy transactions only.<br>
<b>Live</b> = Will be used with you Live PayPal credentials to make actual transaction with normal users with PayPal account.',
        'bluesnap' => 'Bluesnap Payment Method',
        'bluesnap_note' => 'Bluesnap card form for payment',
        'how_to_bluesnap' => 'How to get Bluesnap API Credentials?',
      ),
      'management' => 'General Settings',
      'app_name' => 'App Name',
      'app_url' => 'App URL',
      'lesson_note' => 'Enable / Disable if user will be able to skip before timer is over.',
      'font_color' => 'Font Color',
      'static' => 'Static',
      'google_analytics_id' => 'Google Analytics ID',
      'google_analytics_id_note' => 'How to get Google Analytics ID?',
      'database' => 'Database / Real',
      'counter' => 'Counter',
      'counter_note' => '<b>Static</b> =  Manually add data for counter. Please enter exact text you want to display on frontend counter section,<br> <b>Database/Real</b> = It will take real data from database for all the fields (Students enrolled, Total Courses, Total Teachers)',
      'total_students' => 'Enter Total Students. Ex: 1K, 1Million, 1000 etc.',
      'total_courses' => 'Enter Total Courses. Ex: 1K, 1000 etc.',
      'total_teachers' => 'Enter Total Teachers. Ex: 1K, 1000 etc.',
      'layout_type' => 'Layout Type',
      'theme_layout' => 'Theme Layout',
      'layout_note' => 'This will change frontend theme layout',
      'show_offers_note' => 'Enable / Disable if Coupon offers page link to be displayed in bottom footer',
      'newsletter' => 
      array (
        'mail_provider' => 'Mail Service Provider',
        'mailchimp' => 'Mailchimp',
        'sendgrid' => 'SendGrid',
        'mail_provider_note' => '<b>Note </b>: You can select any Mail service provider to receive all the emails which are being used to <b>subscribe newsletter</b>.<br> Select and setup according to steps given. <b>It is compulsory</b>, if you want to use <b>newsletter subscription</b> form.',
        'api_key' => 'API Key',
        'api_key_note' => 'Generate <b>API key</b> from your <a target="_blank" href="https://mailchimp.com/"><b> Mailchimp account</b></a> and paste that in above text box.',
        'api_key_question' => 'How to generate API key?',
        'list_id' => 'List ID',
        'list_id_note' => 'Find and paste <b>List ID</b> in above box',
        'list_id_question' => 'How to find List ID from Mailchimp?',
        'double_opt_in' => 'Double Opt-in',
        'double_opt_in_note' => '<b>On</b> = User will be asked in mail to opt in for subscription. <b>Off</b> = User will be directly subscribed for newsletter ',
        'api_key_note_sendgrid' => 'Generate <b>API key</b> from your <a target="_blank" href="https://sendgrid.com/"><b> SendGrid account</b></a> and paste that in above text box.',
        'get_lists' => 'Get Lists',
        'sendgrid_lists' => 'SendGrid Email Lists',
        'select_list' => 'Select List',
        'manage_lists' => 'Manage SendGrid Lists',
        'create_new' => 'Create and Select New',
        'title' => 'Newsletter Configuration',
        'list_id_question_sendgrid' => 'Create new Email list for SendGrid Here.',
      ),
      'mail_configuration_note' => 'Have you configured :link Mail Settings</a>? It is compulsory to setup to send/receive emails',
      'app_locale' => 'App Locale',
      'app_timezone' => 'App Timezone',
      'mail_driver' => 'Mail Driver',
      'mail_host' => 'Mail Host',
      'mail_port' => 'Mail Port',
      'mail_from_name' => 'Mail From Name',
      'mail_from_address' => 'Mail From Address',
      'mail_username' => 'Mail Username',
      'mail_password' => 'Mail Password',
      'enable_registration' => 'Enable Registration',
      'change_email' => 'Change Email',
      'password_history' => 'Password History',
      'password_expires_days' => 'Password Expires Days',
      'requires_approval' => 'Requires Approval',
      'confirm_email' => 'Confirm Email',
      'homepage' => 'Select Homepage',
      'captcha_status' => 'Captcha Status',
      'captcha_site_key' => 'Captcha Key',
      'captcha_site_secret' => 'Captcha Secret',
      'google_analytics' => 'Google Analytics Code',
      'sections_note' => 'Once you click on update, you will see list of sections to on/off.',
      'general' => 
      array (
        'title' => 'General',
      ),
      'captcha' => 'Whether the registration - login captcha is on or off',
      'captcha_note' => 'How to get Google reCaptcha credentials?',
      'retest_note' => 'Enable / Disable if user will be able to give retest for same exam',
      'language_settings' => 
      array (
        'title' => 'Language Settings',
        'default_language' => 'Default Language',
        'right_to_left' => 'Right to Left',
        'left_to_right' => 'Left to right',
        'display_type' => 'Display Type',
      ),
      'user_registration_settings' => 
      array (
        'title' => 'User Registration Settings',
        'desc' => 'Checked fields from the right sidebar will be displayed in registration form',
        'fields' => 
        array (
          'first_name' => 'First Name',
          'last_name' => 'Last Name',
          'email' => 'Email',
          'password' => 'Password',
          'phone' => 'Phone',
          'dob' => 'Date of Birth',
          'gender' => 'Gender',
          'male' => 'Male',
          'female' => 'Female',
          'other' => 'Other',
          'address' => 'Address',
          'pincode' => 'Pincode',
          'country' => 'Country',
          'state' => 'State',
          'city' => 'City',
        ),
      ),
      'troubleshoot' => 'Troubleshoot',
      'onesignal_note' => 'Enable / Disble OneSignal configuration for Website.',
      'how_to_onesignal' => 'How to create app in OneSignal?',
      'setup_onesignal' => 'How to set up OneSignal?',
      'api_clients' => 
      array (
        'title' => 'API Clients',
        'generate' => 'Generate',
        'note' => '<span class="text-danger font-weight-bold">Note :</span> This section will be helpful for API purpose. You can generate <b>Client ID</b> and <b>Client Secret</b> to use in your Android app or Postman to test the API.<br> You need to customise parameters and URL according to your requirement.',
        'developer_manual' => 'Developer Manual',
        'fields' =>
        array (
          'name' => 'Name',
          'id' => 'ID',
          'secret' => 'Secret',
          'status' => 'Status',
          'action' => 'Action',
        ),
        'revoked' => 'Revoked',
        'revoke' => 'Revoke',
        'live' => 'Live',
        'enable' => 'Enable',
        'api_client_name' => 'API Client Name',
        'something_went_wrong' => 'Something Went Wrong',
        'please_input_api_client_name' => 'Please input API client name',
      ),
    ),
    'logo' => 
    array (
      'logo_b' => 'Logo 1',
      'logo_b_note' => 'Note : Upload logo with <b>black text and transparent background in .png format</b> and <b>294x50</b>(WxH) pixels.<br> <b>Height</b> should be fixed, <b>width</b> according to your <b>aspect ratio</b>.',
      'logo_w' => 'Logo 2',
      'logo_w_note' => 'Note : Upload logo with <b>white text and transparent background in .png format</b> and <b>294x50</b> (WxH) pixels.<br> <b>Height</b> should be fixed, <b>width</b> according to your <b>aspect ratio</b>.',
      'logo_white' => 'Logo 3',
      'logo_white_note' => 'Note : Upload logo with <b>only in white text and transparent background in .png format</b> and <b>294x50</b>(WxH)  pixels.<br> <b>Height</b> should be fixed, <b>width</b> according to your <b>aspect ratio</b>.',
      'logo_popup' => 'Logo for Popups',
      'logo_popup_note' => 'Note : Add square logo minimum resolution <b>72x72</b> pixels',
      'favicon' => 'Add Favicon',
      'favicon_note' => 'Note : Upload logo with resolution <b>32x32</b> pixels and extension <b>.png</b> or <b>.gif</b> or <b>.ico</b>',
      'title' => 'Change Logo',
    ),
    'social_settings' => 
    array (
      'management' => 'Social Settings',
      'fb_note' => 'Enable / disable facebook login for website',
      'fb_api_note' => 'How to get Facebook API Credentials?',
      'google_api_note' => 'How to get Google API Credentials?',
      'twitter_api_note' => 'How to get Twitter API Credentials?',
      'google_note' => 'Enable / disable Google login for website',
      'twitter_note' => 'Enable / disable Twitter login for website',
      'linkedin_api_note' => 'How to get LinkedIn API Credentials?',
      'linkedin_note' => 'Enable / disable LinkedIn login for website',
    ),
    'hero_slider' => 
    array (
      'fields' => 
      array (
        'name' => 'Name',
        'bg_image' => 'BG Image',
        'overlay' => 
        array (
          'title' => 'Overlay',
          'note' => 'If you turn it on. A black overlay will be displayed on your image. It will be helpful when BG image is not darker or does not have Overlay',
        ),
        'hero_text' => 'Hero Text',
        'sub_text' => 'Sub Text',
        'widget' => 
        array (
          'title' => 'Widget',
          'input_date_time' => 'Input date and time',
          'select_widget' => 'Select Widget',
          'search_bar' => 'Search Bar',
          'countdown_timer' => 'Countdown Timer',
        ),
        'buttons' => 
        array (
          'title' => 'Buttons',
          'add' => 'Add',
          'placeholder' => 'Add number of buttons you want to add',
          'note' => 'Note: Maximum 4 buttons can be added. Please add label and link for the button for redirecting action when button is clicked.',
          'name' => 'Button',
          'label' => 'Label',
          'link' => 'Link',
        ),
        'sequence' => 'Sequence',
        'status' => 'Status',
      ),
      'note' => 'Note: Please upload .jpg or .png in <b>1920x900</b> resolution for best result. Use darker or Overlayed images for better result.',
      'on' => 'On',
      'off' => 'Off',
      'title' => 'Hero Slider',
      'create' => 'Create Slide',
      'edit' => 'Edit Slide',
      'view' => 'View Slides',
      'manage_sequence' => 'Manage Sequence of Slides',
      'sequence_note' => 'Drag and change sequence of a Slide',
      'save_sequence' => 'Save Sequence',
    ),
    'tax' => 
    array (
      'title' => 'Tax',
      'create' => 'Cipta Tax',
      'edit' => 'Edit Tax',
      'view' => 'Papar Tax',
      'on' => 'On',
      'off' => 'Off',
      'fields' => 
      array (
        'name' => 'Nama',
        'rate' => 'Rate',
        'status' => 'Status',
      ),
    ),
    'coupons' => 
    array (
      'title' => 'Kupon',
      'create' => 'Cipta Kupon',
      'edit' => 'Edit Kupon',
      'view' => 'Papar Kupon',
      'courses' => 'Kursus',
      'bundles' => 'Bundles',
      'on' => 'On',
      'off' => 'Off',
      'flat_rate' => 'Flat Rate',
      'discount_rate' => 'Discount Rate',
      'type_note' => '<b>Discount Rate (%) :</b> If you will select this, it will apply rate in % to total purchase. Ex. Price = $100 and Discount rate is 10% then 10% of 100$ will be deducted.<br><b>Flat Rate : </b>If you select this, particular amount will be deducted from total purchase. Ex. Price = 100$ and Flat rate is 25$ then 25$ will be deducted from 100$.',
      'amount_note' => 'If <b>Discount Rate</b> selected, input rate of percentage. If <b>Flat Rate</b> selected, input particular amount to be deducted.',
      'per_user_limit_note' => 'Specify how many times a single user can use this coupon. By default one time use.',
      'total_note' => 'Number of coupons to be issued',
      'fields' => 
      array (
        'name' => 'Name',
        'code' => 'Code',
        'type' => 'Type',
        'for' => 'For',
        'amount' => 'Amount',
        'expires_at' => 'Expires At',
        'per_user_limit' => 'Per User Limit',
        'total' => 'Total',
        'status' => 'Status',
        'min_price' => 'Minimum Order Price',
        'description' => 'Description',
      ),
      'description' => 'Description',
      'unlimited' => 'Unlimited',
    ),
    'sponsors' => 
    array (
      'title' => 'Sponsors',
      'fields' => 
      array (
        'name' => 'Name',
        'link' => 'Link',
        'logo' => 'Logo',
        'status' => 'Status',
      ),
      'create' => 'Create Sponsors',
      'edit' => 'Edit Sponsors',
      'view' => 'View Sponsors',
    ),
    'teachers' => 
    array (
      'fields' => 
      array (
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'email' => 'Email Address',
        'password' => 'Password',
        'image' => 'Image',
        'status' => 'Status',
      ),
      'title' => 'Teachers',
      'create' => 'Create Teacher',
      'edit' => 'Edit Teacher',
      'view' => 'View Teachers',
    ),
    'testimonials' => 
    array (
      'fields' => 
      array (
        'name' => 'Name',
        'occupation' => 'Occupation',
        'content' => 'Content',
        'status' => 'Status',
      ),
      'title' => 'Testimonials',
      'create' => 'Create Testimonial',
      'edit' => 'Edit Testimonial',
      'view' => 'View Testimonials',
    ),
    'dashboard' => 
    array (
      'title' => 'Dashboard',
      'students' => 'Pelajar',
      'trending' => 'Berbayar',
      'teachers' => 'Pengajar',
      'completed' => 'Lengkap',
      'no_data' => 'Data tidak ada',
      'buy_course_now' => 'Ambil Kursus',
      'your_courses' => 'Kursus Anda',
      'students_enrolled' => 'Pengajar yang ambil<br> Kursus Anda',
      'recent_reviews' => 'Ulasan Terkini',
      'recent_orders' => 'Pesanan Terkini',
      'recent_contacts' => 'Kenalan Terkini',
      'view_all' => 'Lihat semua',
      'course' => 'Kursus',
      'review' => 'Review',
      'time' => 'Masa',
      'recent_messages' => 'Mesej Terkini',
      'message' => 'Mesej',
      'message_by' => 'Mesej oleh',
      'courses' => 'Kursus',
      'ordered_by' => 'Dipesan Oleh',
      'view' => 'Papar',
      'amount' => 'Jumlah',
      'recent_contact_requests' => 'Permintaan Kenalan Terkini',
      'name' => 'Nama',
      'email' => 'Email',
      'my_course_bundles' => 'Kursus Bundle',
      'my_courses' => 'Kursus saya',
      'your_courses_and_bundles' => 'Kursus dan Bundle Anda',
      'course_and_bundles' => 'Kursus dan Bundles',
      'pending_orders' => 'Pesanan Belum Selesai',
      'pending' => 'Dalam Proses',
      'success' => 'Berjaya',
      'failed' => 'Gagal',
    ),
    'questions_options' => 
    array (
      'title' => 'Pilihan Soalan',
      'create' => 'Cipta Pilihan',
      'edit' => 'Edit Pilihan',
      'view' => 'View Soalan Pilihan',
      'fields' => 
      array (
        'course' => 'Kursus',
        'lesson' => 'Lesson',
        'title' => 'Tajuk',
        'question' => 'Soalan',
        'question_option' => 'Soalan Pilihan',
        'score' => 'Markah',
        'tests' => 'Ujian',
        'option_text' => 'Pilihan Text',
        'correct' => 'Betul',
      ),
    ),
    'reviews' => 
    array (
      'title' => 'Reviews',
      'fields' => 
      array (
        'course' => 'Kursus',
        'user' => 'User',
        'content' => 'Content',
        'time' => 'Masa',
      ),
    ),
    'contacts' => 
    array (
      'title' => 'Leads',
      'fields' => 
      array (
        'name' => 'Name',
        'email' => 'Email',
        'phone' => 'Phone',
        'message' => 'Mesej',
        'time' => 'Masa',
      ),
    ),
    'translations' => 
    array (
      'title' => 'Translation Manager',
      'warning' => 'Warning, translations are not visible until they are exported back to the app/lang file, using
                        <code>php artisan translation:export</code> command or publish button.',
      'done_importing' => 'Done importing, processed <strong class="counter">N</strong> items! Reload this page to
                            refresh the groups!',
      'done_searching' => 'Done searching for translations, found <strong class="counter">N</strong> items!',
      'done_publishing_for_group' => 'Done publishing the translations for group',
      'done_publishing_for_all_groups' => 'Done publishing the translations for all group!',
      'append_new_translations' => 'Append new translations',
      'replace_existing_translations' => 'Replace existing translations',
      'import_groups' => 'Import Groups',
      'import_groups_note' => '<p>This will get all locale files from <code>lang</code> folder and insert into database.<br> <b>Append new translations :</b> It will append only new files and data <b>&amp;</b>
                                            <b>Replace existing translations:</b>It will replace existing records according to files</p>',
      'choose_a_group' => 'Choose a group to display the group translations. If no groups are visible, make sure
                                you have run the migrations and imported the translations.',
      'translation_warning' => 'Are you sure you want to publish the translations group :group ? This will overwrite existing language files',
      'publishing' => 'Publishing..',
      'publish_translations' => 'Publish Translations',
      'total' => 'Total',
      'changed' => 'Changed',
      'key' => 'Key',
      'supported_locales' => 'Supported Locales',
      'current_supported_locales' => 'Current Supported Locales',
      'enter_new_locale_key' => 'Enter new locale key',
      'add_new_locale' => 'Add new locale',
      'adding' => 'Adding...',
      'export_all_translations' => 'Export all translations',
      'publish_all' => 'Publish all',
      'publish_all_warning' => 'Are you sure you want to publish all translations group? This will overwrite existing language files.',
    ),
    'update' => 
    array (
      'title' => 'Update Theme',
      'upload' => 'Upload new version  <small>(update.zip)</small>',
      'current_version' => 'Current Version',
      'note_before_upload_title' => 'Read following notes before updating',
      'file_replaced' => 'Following files will be updated / replaced',
      'warning' => '<b>WARNING : We strongly recommend you to update theme by version number</b>.<br> <b>Example :</b> update_v1.zip, update_v2.zip. Please do not jump version number. If your version number is 1 and you want to update it, then update to version 2. Do no directly update to version 3.',
      'note_before_upload' => '<p><b>Please take BACKUP before updating.</b> Updated zip file may come with new folders and file updates. <b>Your current files will be replaced with new one</b>. So, <b>if you have made any changes in current application files it will be LOST</b>.</p>
                        <p>If you are directly uploading from below file input box, your files will be replaced. We strongly recommend you to do it manual replacement of files one by one or edit the changes by comparing your current edited file and new updated files.</p>
                        <p>If you still have confusion. Please contact us, we will guide you to update your application</p>',
    ),
    'backup' => 
    array (
      'title' => 'Backup',
      'email' => 'Email Notification',
      'app_token' => 'App Token',
      'app_secret' => 'App Secret',
      'api_key' => 'API Key',
      'app_key' => 'App Key',
      'api_secret' => 'API Secret',
      'enable_disable' => 'Enable / Disable',
      'backup_type' => 'Backup Type',
      'dropbox' => 'Dropbox',
      'backup_files' => 'Backup Files',
      'aws' => 'AWS S3',
      'db' => 'Database',
      'configuration' => 'Configuration',
      'generate_backup' => 'Generate Backup',
      'db_storage' => 'Database and Storage files',
      'db_app' => 'Database and Application files',
      'backup_schedule' => 'Backup Schedule',
      'daily' => 'Daily',
      'weekly' => 'Weekly',
      'monthly' => 'Monthly',
      'dropbox_note' => 'Please checkout documentation for <b>How to obtain DropBox App Keys?</b>',
      'region' => 'Region',
      'bucket_name' => 'Bucket Name',
      'backup_notice' => 'Please refer documentation before beginning backup. It has every details step by step for creating backup with Dropbox.',
      'backup_note' => '<b>Note </b>: To run this backup properly you need to add following code to your <b>CRON TAB:</b><br><code>* * * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1</code>',
    ),
    'certificates' => 
    array (
      'title' => 'Certificates',
      'fields' => 
      array (
        'course_name' => 'Nama Kursus',
        'progress' => 'Progress',
        'action' => 'Tindakan',
      ),
      'view' => 'View',
      'download' => 'Download',
    ),
    'bundles' => 
    array (
      'title' => 'Bundles',
      'fields' => 
      array (
        'published' => 'Diterbitkan',
        'featured' => 'Percuma',
        'trending' => 'Berbayar',
        'free' => 'Berbayar',
        'popular' => 'Popular',
        'teachers' => 'Pengajar',
        'category' => 'Kategori',
        'title' => 'Tajuk',
        'slug' => 'Slug',
        'description' => 'Huraian',
        'price' => 'Harga',
        'course_image' => 'Gambar Kursus',
        'start_date' => 'Tarikh Mula',
        'meta_title' => 'Meta Title',
        'meta_description' => 'Meta Huraian',
        'meta_keywords' => 'Meta Keywords',
        'sidebar' => 'Tambah Sidebar',
        'lessons' => 
        array (
          'add' => 'Tambah Lessons',
          'view' => 'Papar Lessons',
        ),
        'course' => 'Kursus',
        'courses' => 'Kursus',
        'status' => 'Status',
      ),
      'add_courses' => 'Tambah Kursus',
      'add_teachers' => 'Tambah Pengajar',
      'add_categories' => 'Tambah Kategori',
      'slug_placeholder' => 'Input slug or it will be generated automatically',
      'select_category' => 'Pilih Kategori',
      'select_courses' => 'Pilih Kursus',
      'select_teachers' => 'Pilih Pengajar',
      'test' => 'Ujian',
      'lesson' => 'Lesson',
      'create' => 'Cipta Bundle',
      'edit' => 'Edit Bundle',
      'view' => 'Papar Bundles',
      'category' => 'Kategori',
      'save_timeline' => 'Save timeline',
      'course_timeline' => 'Kursus timeline',
      'timeline_description' => 'Drag and change sequence of Lessons/Tests for course',
      'listing_note' => 'Only Published Lessons and Tests will be Displayed and Sorted.',
    ),
    'reports' => 
    array (
      'title' => 'Laporan',
      'sales_report' => 'Laporan Jualan',
      'students_report' => 'Laporan Pelajar',
      'bundles' => 'Bundles',
      'courses' => 'Kursus',
      'total_earnings' => 'Jumlah pendapatan',
      'total_sales' => 'Jumlah jualan',
      'fields' => 
      array (
        'name' => 'Nama',
        'orders' => 'Pesanan',
        'earnings' => 'Pendapatan',
        'course' => 'Kursus',
        'user' => 'User',
        'content' => 'Content',
        'time' => 'Masa',
        'students' => 'Pelajar',
        'bundle' => 'Bundle',
        'completed' => 'Kursus Yang Selesai',
      ),
    ),
    'sitemap' => 
    array (
      'title' => 'Sitemap',
      'records_per_file' => 'Records Per File',
      'records_note' => 'Number of records per file.',
      'generated' => 'Sitemap generated successfully.',
      'generate' => 'Generate',
      'daily' => 'Harian',
      'weekly' => 'Mingguan',
      'monthly' => 'Bulanan',
      'sitemap_note' => 'This sitemap tool will generate sitemap for published Course, Bundles and Blog.',
    ),
    'forum_category' => 
    array (
      'title' => 'Kategori Forum',
      'create' => 'Cipta Kategori Forum',
      'edit' => 'Edit Kategori Forum',
      'view' => 'Papar Kategori Forum',
      'on' => 'On',
      'off' => 'Off',
      'fields' => 
      array (
        'parent_category' => 'Kategori Ibu Bapa',
        'category' => 'Kategori',
        'order' => 'Pesanan',
        'color' => 'Warna',
        'status' => 'Status',
      ),
    ),
  ),
  'general' => 
  array (
    'active' => 'Active',
    'inactive' => 'Inactive',
    'yes' => 'Yes',
    'no' => 'No',
    'none' => 'None',
    'back' => 'Back',
    'more' => 'More',
    'buttons' => 
    array (
      'update' => 'Update',
      'cancel' => 'Cancel',
      'save' => 'Save',
    ),
    'toolbar_btn_groups' => 'Toolbar with button groups',
    'create_new' => 'Cipta Baru',
    'all' => 'Semua',
    'trash' => 'Buangan',
    'delete' => 'Padam',
    'no_data_available' => 'Tiada data yang wujud',
    'edit' => 'Edit',
    'copyright' => 'Copyright',
    'delete_selected' => 'Padam yang dipilih',
    'custom' => 'Custom',
    'actions' => 'Actions',
    'hide' => 'Sembunyikan',
    'show' => 'Papar',
    'toggle_navigation' => 'Toggle Navigation',
    'sr_no' => 'Sr No.',
    'read_more' => 'Baca Lagi',
  ),
  'frontend' => 
  array (
    'auth' => 
    array (
      'login_button' => 'Log masuk',
      'login_box_title' => 'Log masuk',
      'remember_me' => 'Remember Me',
      'register_box_title' => 'Daftar',
      'register_button' => 'Daftar',
      'login_with' => 'Daftar dengan :social_media',
    ),
    'passwords' => 
    array (
      'reset_password_box_title' => 'Reset Password',
      'send_password_reset_link_button' => 'Send Password Reset Link',
      'expired_password_box_title' => 'Password anda telah tamat tempoh.',
      'update_password_button' => 'Password Kemaskini',
      'reset_password_button' => 'Reset Password',
      'forgot_password' => 'Lupa Password Anda?',
    ),
    'blog' => 
    array (
      'share_this_news' => 'Kongsi Berita Ini',
      'related_news' => '<span>Related</span> News',
      'post_comments' => 'Post <span>Comments.</span>',
      'write_a_comment' => 'Tulis Komen',
      'add_comment' => 'Tambah Komen',
      'by' => 'By',
      'title' => 'Blog',
      'search_blog' => 'Cari Blog',
      'blog_categories' => 'Blog <span>Categories.</span>',
      'popular_tags' => 'Popular <span>Tags.</span>',
      'featured_course' => 'Percuma <span>Course.</span>',
      'login_to_post_a_comment' => 'Log masuk untuk Menghantar Komen',
      'no_comments_yet' => 'Belum ada komen, Jadilah yang pertama memberi komen.',
    ),
    'cart' => 
    array (
      'payment_status' => 'Status bayaran',
      'payment_cards' => 'Kad Kredit Atau Kad Debit',
      'name_on_card_placeholder' => 'Masukkan nama yang tertera pada kad anda',
      'no_payment_method' => 'Tidak ada kaedah pembayaran yang tersedia buat masa ini',
      'card_number_placeholder' => 'Masukkan nombor kad anda',
      'cvv' => 'CVV',
      'mm' => 'MM',
      'yy' => 'YY',
      'pay_now' => 'Bayar Sekarang',
      'stripe_error_message' => 'Betulkan kesilapan dan cuba lagi.',
      'paypal' => 'Online Banking',
      'pay_securely_paypal' => 'Bayar dengan Billplz',
      'offline_payment' => 'Offline Payment',
      'offline_payment_note' => 'Sila Whatsapp kami untuk maklumat lanjur',
      'request_assistance' => 'Daftar Kursus',
      'cart' => 'Troli',
      'checkout' => 'Checkout',
      'your_shopping_cart' => 'Troli Pembelian Anda',
      'complete_your_purchases' => 'Lengkapkan<span> Pembelian anda.</span>',
      'order_item' => 'Order <span>Item.</span>',
      'course_name' => 'Nama Kursus',
      'course_type' => 'Jenis Kursus',
      'starts' => 'Mula',
      'empty_cart' => 'Troli anda masih kosong',
      'order_payment' => 'Order <span>Payment.</span>',
      'name_on_card' => 'Nama pada kad',
      'card_number' => 'Nombor Kad',
      'expiration_date' => 'Expiration Date',
      'confirmation_note' => 'Dengan setuju pembelian ini, saya setuju dengan <b>Terma dan Syarat</b> dan <b>Polisi Privasi</b>',
      'order_detail' => 'Order <span>Detail.</span>',
      'total' => 'Jumlah',
      'your_payment_status' => 'Status Pembayaran <span>Anda.</span>',
      'success_message' => 'Tahniah. Selamat Belajar!',
      'see_more_courses' => 'Lihat Kursus Lain',
      'go_back_to_cart' => 'Balik kepada troli',
      'product_name' => 'Nama kursus',
      'product_type' => 'Jenis Produk',
      'product_added' => 'Kursus berjaya ditambahkan ke troli',
      'try_again' => 'Kesilapan! Sila cuba lagi.',
      'payment_done' => 'Pembayaran berjaya dilakukan !',
      'payment_failed' => 'Kesilapan! Pembayaran gagal!',
      'offline_request' => 'Permintaan berjaya diterima! periksa e-mel berdaftar anda untuk maklumat lebih lanjut.',
      'purchase_successful' => 'Tahniah! Anda telah membeli kursus ini.',
      'unknown_error' => 'Unknown error occurred',
      'connection_timeout' => 'Connection Timeout',
      'sub_total' => 'Sub Total',
      'apply' => 'Apply',
      'items' => 'items',
      'item' => 'item',
      'offers' => 'Offers',
      'empty_input' => 'Tulis kod kupon sebelum memohon',
      'invalid_coupon' => 'Kupon Tidak Sah!',
      'amount' => 'Jumlah',
      'total_payable' => 'Jumlah Keseluruhan',
      'price' => 'Harga',
    ),
    'contact' => 
    array (
      'title' => 'Contact',
      'your_name' => 'Your Name',
      'your_email' => 'Your Email',
      'phone_number' => 'Phone Number',
      'message' => 'Message',
      'box_title' => 'Contact Us',
      'button' => 'Send Information',
      'send_us_a_message' => 'Send Us A<span> Message.</span>',
      'keep_in_touch' => 'Keep<span> In Touch.</span>',
      'send_email' => 'Send Email',
      'send_message_now' => 'Send Message Now',
    ),
    'badges' => 
    array (
      'trending' => 'Berbayar',
    ),
    'course' => 
    array (
      'ratings' => 'Ratings',
      'stars' => 'Stars',
      'by' => 'By',
      'no_reviews_yet' => 'Belum ada ulasan.',
      'add_to_cart' => 'Tambah ke troli',
      'buy_note' => 'Hanya Pelajar Yang Boleh Membeli Kursus',
      'continue_course' => 'Mula Belajar',
      'enrolled' => 'Telah Daftar',
      'chapters' => 'Modul',
      'category' => 'Kategori',
      'author' => 'Pengajar',
      'courses' => 'Kursus',
      'students' => 'Pelajar',
      'give_test_again' => 'Give Test Again',
      'submit_results' => 'Hantar Keputusan',
      'chapter_videos' => 'Video Modul',
      'download_files' => 'Download Files',
      'mb' => 'MB',
      'prev' => 'PREV',
      'test' => 'Ujian',
      'completed' => 'Lengkap',
      'title' => 'Kursus',
      'course_details' => '<span>Maklumat Kursus.</span>',
      'course_detail' => 'Maklumat Kursus',
      'course_timeline' => 'Modul <b>Kursus:</b>',
      'go' => 'Go',
      'course_reviews' => 'Ulasan <span>Kursus:</span>',
      'average_rating' => 'Purata Rating',
      'details' => 'Perincian',
      'add_reviews' => 'Tambah <span>Ulasan.</span>',
      'your_rating' => 'Rating anda',
      'message' => 'Mesej',
      'add_review_now' => 'Tambah Ulasan Sekarang',
      'price' => 'Price',
      'added_to_cart' => 'Ditambah Ke Troli',
      'buy_now' => 'Ambil Kursus',
      'get_now' => 'Belajar Sekarang',
      'recent_news' => '<span>Berita </span>Weekan.',
      'view_all_news' => 'Papar Semua Berita Weekan',
      'featured_course' => '<span>Kursus</span> Percuma.',
      'sort_by' => '<b>Disusun</b> Mengikuti',
      'popular' => 'Trending',
      'none' => 'Biasa',
      'trending' => 'Berbayar',
      'featured' => 'Percuma',
      'course_name' => 'Nama Kursus',
      'course_type' => 'Kursus Percuma',
      'starts' => 'Mula',
      'full_text' => 'Text Penuh',
      'find_courses' => 'CARI KURSUS',
      'your_test_score' => 'Markah Ujian Anda',
      'find_your_course' => '<span>Cari </span>Kursus Anda.',
      'next' => 'Seterusnya',
      'progress' => 'Kemajuan',
      'finish_course' => 'Kursus Yang Selesai',
      'certified' => 'Anda telah mendapat sikil kursus ini',
      'course' => 'Kursus',
      'bundles' => 'Bundles',
      'bundle_detail' => 'Maklumat Bundle',
      'bundle_reviews' => 'Ulasan <span>Bundle:</span>',
      'available_in_bundles' => 'Juga terdapat dalam Bundles',
      'complete_test' => 'Sila Lengkapkan Ujian',
      'looking_for' => 'Sedang Mencari?',
      'not_attempted' => 'Tidak Attempted',
      'explanation' => 'Penerangan',
      'find_your_bundle' => '<span>Cari</span> Bundle Anda',
      'select_category' => 'Pilih Kategori',
    ),
    'home' => 
    array (
      'title' => 'Home',
      'search_course_placeholder' => 'Cari Kursus Yang Anda Ingin Belajar',
      'popular_teachers' => '<span>Pengajar</span> Kami',
      'learn_new_skills' => 'Belajar Kemahiran Baru',
      'search_course' => 'Cari Kursus',
      'search_courses' => '<span>Cari</span> Kursus.',
      'students_enrolled' => 'Jumlah Pelajar',
      'online_available_courses' => 'Jumlah Kursus',
      'teachers' => 'Pengajar',
      'our_professionals' => 'Belajar dengan mereka',
      'all_teachers' => 'Semua Pengajar',
      'what_they_say_about_us' => 'Apa Komen Pelajar',
    ),
    'layouts' => 
    array (
      'partials' => 
      array (
        'advantages' => 'Kelebihan',
        'email_address' => 'Alamat emel',
        'email_registration' => 'E-mel Kami Untuk Pendaftaran Percuma',
        'call_us_registration' => 'Hubungi Kami Untuk Pendaftaran Percuma',
        'students' => 'Pelajar',
        'faq' => 'FAQ',
        'more_faqs' => 'More Faqs',
        'search_placeholder' => 'Cari Kursus Yang Anda Ingin Belajar',
        'search_our_courses' => 'CARI KURSUS',
        'browse_featured_course' => 'Cari<span> Kursus Berbayar.</span>',
        'course_detail' => 'Marklumat Kursus',
        'contact_us' => 'Hubungi Kami',
        'get_in_touch' => 'Hubungi',
        'primary' => 'Utama',
        'second' => 'Second',
        'courses_categories' => 'Kategori Kursus',
        'browse_course_by_category' => 'Cari Kursus<span> Berdasarkan Kategori.</span>',
        'faq_full' => 'Frequently<span> Asked Questions</span>',
        'social_network' => 'Media Sosial',
        'subscribe_newsletter' => 'Langgan Newsletter',
        'subscribe_now' => 'langgan Sekarang',
        'latest_news_blog' => 'Artikel <span>Terbaru.</span>',
        'trending_courses' => 'Kursus <span>Berbayar.</span>',
        'popular_courses' => 'Kursus <span>Trending.</span>',
        'view_all_news' => 'Papar semua berita',
        'view_all_trending_courses' => 'Papar Semua Kursus Berbayar',
        'view_all_popular_courses' => 'Papar Semua Kursus Trending',
        'learn_new_skills' => 'Belajar Kemahiran Baru',
        'recent_news' => '<span>Berita  </span>Terkini.',
        'featured_course' => '<span>Kursus  </span>Percuma.',
        'days' => 'Hari',
        'hours' => 'Jam',
        'minutes' => 'Minit',
        'seconds' => 'Saat',
        'search_courses' => 'Cari Kursus',
        'sponsors' => 'Sponsors.',
        'students_testimonial' => 'Testimoni <span>Pelajar.</span>',
        'why_choose' => 'Kelebihan Weekan',
        'certificate_verification' => 'Certificate Verification',
        'offers' => 'Tawaran',
      ),
    ),
    'modal' => 
    array (
      'new_user_note' => 'Pengguna baru? Daftar disini',
      'registration_message' => 'Pendaftaran berjaya. Sila daftar masuk',
      'my_account' => 'Akaun saya',
      'login_register' => '<a href="#" class="font-weight-bold go-login px-0">LOGIN</a> to our website, or <a href="#" class="font-weight-bold go-register px-0" id="">REGISTER</a>',
      'already_user_note' => 'Sudah menjadi pengguna? Daftar masuk disini',
      'login_now' => 'Log masuk sekarang',
      'register_now' => 'Daftar sekarang',
    ),
    'search_result' => 
    array (
      'students' => 'Pelajar',
      'blog' => 'Blog',
      'search_blog' => 'Cari Blog',
      'sort_by' => '<b>Disusun</b> Mengikuti',
      'popular' => 'Trending',
      'none' => 'None',
      'trending' => 'Berbayar',
      'featured' => 'Percuma',
      'course_name' => 'Nama Kursus',
      'course_type' => 'Jenis Kursus',
      'starts' => 'Mula',
      'course_detail' => 'Maklumar Kursus',
    ),
    'teacher' => 
    array (
      'send_now' => 'Hantar Sekarang',
      'students' => 'Pelajar',
      'title' => 'Pengajar',
      'courses_by_teacher' => 'Kursus <span>Daripada Pengajar.</span>',
      'course_detail' => 'Maklumat Kursus',
    ),
    'user' => 
    array (
      'passwords' => 
      array (
        'change' => 'Tukar Kata laluan',
      ),
      'profile' => 
      array (
        'avatar' => 'Avatar',
        'created_at' => 'Dicipta pada',
        'edit_information' => 'Ubah Maklumat',
        'email' => 'E-mail',
        'last_updated' => 'Terakhir dikemas kini',
        'name' => 'Nama',
        'first_name' => 'Nama pertama',
        'last_name' => 'Nama terakhir',
        'update_information' => 'Kemas kini Maklumat',
      ),
    ),
    'faq' => 
    array (
      'title' => 'Frequently <span>Asked Questions</span>',
      'find' => 'Find <span>Your Questions & Answers.</span>',
      'make_question' => 'Make Question',
      'contact_us' => 'Contact Us',
    ),
    'certificate_verification' => 
    array (
      'title' => 'Certificate Verification',
      'name_on_certificate' => 'Name on Certificate. Ex. John',
      'date_on_certificate' => 'Date on Certificate. Ex. 2018-11-25',
      'verify_now' => 'Verify Now',
      'not_found' => 'No certificate found for given information.',
    ),
    'footer' => 
    array (
      'popular_courses' => 'Kursus Trending',
      'popular_categories' => 'Kategori Trending',
      'featured_courses' => 'Kursus Percuma',
      'trending_courses' => 'Kursus Berbayar',
      'useful_links' => 'Useful Links',
    ),
    'offers' => 
    array (
      'title' => 'Tawaran',
      'no_offers' => 'Tiada Tawaran',
      'unlimited' => 'Unlimited',
      'validity' => 'Validity',
      'minimum_order_amount' => 'Minimum Order Amount',
      'usage' => 'Usage',
      'per_user' => 'Per User',
    ),
  ),
  'lang' => 
  array (
    'en' => 'English',
    'sp' => 'Spanish',
    'fr' => 'French',
    'ar' => 'Arabic',
  ),
);
